# Generated by Django 5.0.3 on 2024-03-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MerchType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="artist",
            name="group",
        ),
        migrations.AddField(
            model_name="artist",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/artist"),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/group"),
                ),
                ("artist", models.ManyToManyField(blank=True, to="Articles.artist")),
            ],
        ),
    ]
