# Generated by Django 5.0.3 on 2024-04-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0002_merch_merchtype_remove_artist_group_artist_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merch",
            name="artist",
            field=models.ManyToManyField(blank=True, to="Articles.artist"),
        ),
        migrations.AddField(
            model_name="merch",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Articles.group",
            ),
        ),
        migrations.AddField(
            model_name="merch",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/merch"),
        ),
    ]
