# Generated by Django 5.0.3 on 2024-04-07 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0003_merch_artist_merch_group_merch_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="bias",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merch",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merch",
            name="exchangeSale",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merch",
            name="merchType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Articles.merchtype",
            ),
        ),
        migrations.AddField(
            model_name="merch",
            name="own",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merch",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merch",
            name="wishList",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchtype",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="merch",
            name="group",
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/event"),
                ),
                ("version", models.CharField(blank=True, max_length=200, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("group", models.ManyToManyField(blank=True, to="Articles.group")),
            ],
        ),
        migrations.AddField(
            model_name="merch",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Articles.event",
            ),
        ),
        migrations.AddField(
            model_name="merch",
            name="group",
            field=models.ManyToManyField(blank=True, to="Articles.group"),
        ),
    ]
